Fixed error caused by non- ASCII char
  File "interpret.py", line 2
SyntaxError: Non-ASCII character '\xc2' in file interpret.py on line 2,
but no encoding declared; see http://python.org/dev/peps/pep-0263/ for
details